food_ordering/food_ordering/urls.py
from django.urls import path, include

urlpatterns = [
    path('foods/', include('foods.urls')),
    path('admins/', include('admins.urls')),
    path('', include('accounts.urls'))
]

food_ordering/foods/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('homepage', views.homepage),
    path('category_form', views.category_form),
    path('get_category', views.get_category),
    path('delete_category/<int:category_id>', views.delete_category),
    path('update_category/<int:category_id>', views.category_update_form),

    path('food_form', views.food_form),
    path('get_food', views.get_food),
    path('delete_food/<int:food_id>', views.delete_food),
    path('update_food/<int:food_id>', views.food_update_form),

    path('get_category_user', views.show_categories),
    path('get_food_user', views.show_foods),
    path('menu', views.menu),
    path('add_to_cart/<int:food_id>',views.add_to_cart),
    path('mycart', views.show_cart_items),
    path('remove_cart_item/<int:cart_id>', views.remove_cart_item),
    path('order_form/<int:food_id>/<int:cart_id>', views.order_form),
    path('my_order', views.my_order),
    path('esewa_verify', views.esewa_verify),

]

food_ordering/foods/models.py
from django.db import models
from django.core.validators import *
from django.core import validators
from django.contrib.auth.models import User

class Category(models.Model):
    category_name = models.CharField(max_length=200, null=True, validators=[validators.MinLengthValidator(2)])
    category_description = models.TextField(null=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    category_image = models.FileField(upload_to='static/uploads', null=True)

    def __str__(self):
        return self.category_name


class Food(models.Model):
    food_name = models.CharField(max_length=200)
    food_price = models.FloatField()
    food_image = models.FileField(upload_to='static/uploads')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.food_name


class Cart(models.Model):
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)


class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Delivered', 'Delivered'),
    )
    PAYMENT = (
        ('Cash On Delivery', 'Cash On Delivery'),
        ('Esewa', 'Esewa'),
        ('Khalti', 'Khalti'),
    )
    food = models.ForeignKey(Food, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    quantity = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(1000)])
    total_price = models.IntegerField(null=True)
    status = models.CharField(max_length=200, choices=STATUS, null=True)
    payment_method = models.CharField(max_length=200, choices=PAYMENT, null=True)
    payment_status = models.BooleanField(default=False, null=True, blank=True)
    contact_no = models.CharField(validators=[MinLengthValidator(9), MaxLengthValidator(10)], null=True, max_length=10)
    contact_address = models.CharField(max_length=200, null=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True)

food_ordering/foods/forms.py
from django import forms
from django.forms import ModelForm

from .models import Category, Food, Order

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = "__all__"


class FoodForm(ModelForm):
    class Meta:
        model = Food
        fields = "__all__"


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['quantity', 'contact_no', 'contact_address', 'payment_method']

food_ordering/foods/views.py
from django.shortcuts import render, redirect
from .forms import CategoryForm, FoodForm, OrderForm
from django.contrib import messages
from .models import Category, Food, Cart, Order

from accounts.auth import admin_only, user_only
from django.contrib.auth.decorators import login_required
import os


def homepage(request):
    return render(request, 'foods/homepage.html')


@login_required
@admin_only
def category_form(request):
    if request.method == "POST":
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Category added successfully')
            return redirect("/foods/get_category")
        else:
            messages.add_message(request, messages.ERROR, 'Unable to add category')
            return render(request, 'foods/category_form.html', {'form_category':form})
    context ={
        'form_category': CategoryForm,
        'activate_category': 'active'
    }
    return render(request, 'foods/category_form.html', context)

@login_required
@admin_only
def get_category(request):
    categories =  Category.objects.all().order_by('-id')
    context = {
        'categories':categories,
        'activate_category':'active'
    }
    return render(request, 'foods/get_category.html', context)


@login_required
@admin_only
def delete_category(request, category_id):
    category = Category.objects.get(id=category_id)
    category.delete()
    messages.add_message(request, messages.SUCCESS, 'Category Deleted Successfully')
    return redirect('/foods/get_category')



@login_required
@admin_only
def category_update_form(request, category_id):
    category = Category.objects.get(id=category_id)
    if request.method == "POST":
        form = CategoryForm(request.POST,instance=category)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Category updated successfully')
            return redirect("/foods/get_category")
        else:
            messages.add_message(request, messages.ERROR, 'Unable to update category')
            return render(request, 'foods/category_update_form.html', {'form_category':form})
    context ={
        'form_category': CategoryForm(instance=category),
        'activate_category': 'active'
    }
    return render(request, 'foods/category_update_form.html', context)

@login_required
@admin_only
def food_form(request):
    if request.method == "POST":
        form = FoodForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Food added successfully')
            return redirect("/foods/get_food")
        else:
            messages.add_message(request, messages.ERROR, 'Unable to add food')
            return render(request, 'foods/food_form.html', {'form_food':form})
    context ={
        'form_food': FoodForm,
        'activate_food': 'active'
    }
    return render(request, 'foods/food_form.html', context)


@login_required
@admin_only
def get_food(request):
    foods =  Food.objects.all().order_by('-id')
    context = {
        'foods':foods,
        'activate_food':'active'
    }
    return render(request, 'foods/get_food.html', context)


@login_required
@admin_only
def delete_food(request, food_id):
    food = Food.objects.get(id=food_id)
    os.remove(food.food_image.path)
    food.delete()
    messages.add_message(request, messages.SUCCESS, 'Food Deleted Successfully')
    return redirect('/foods/get_food')


@login_required
@admin_only
def food_update_form(request, food_id):
    food = Food.objects.get(id=food_id)
    if request.method == "POST":
        if request.FILES.get('food_image'):
            os.remove(food.food_image.path)
        form = FoodForm(request.POST, request.FILES, instance=food)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Food updated successfully')
            return redirect("/foods/get_food")
        else:
            messages.add_message(request, messages.ERROR, 'Unable to update food')
            return render(request, 'foods/food_form.html', {'form_food':form})
    context ={
        'form_food': FoodForm(instance=food),
        'activate_food': 'active'
    }
    return render(request, 'foods/food_update_form.html', context)


def show_categories(request):
    categories = Category.objects.all().order_by('-id')
    context = {
        'categories':categories,
        'activate_category_user': 'active'
    }
    return render(request, 'foods/show_categories.html', context)


def show_foods(request):
    foods = Food.objects.all().order_by('-id')
    context = {
        'foods':foods,
        'activate_food_user': 'active'
    }
    return render(request, 'foods/show_foods.html', context)

def menu(request):
    categories  = Category.objects.all().order_by('-id')
    context = {
        'categories':categories,
        'activate_menu':'active'
    }
    return render(request, 'foods/menu.html', context)

@login_required
@user_only
def add_to_cart(request, food_id):
    user = request.user
    food = Food.objects.get(id=food_id)

    check_item_presence = Cart.objects.filter(user=user, food=food)
    if check_item_presence:
        messages.add_message(request, messages.ERROR, 'Item is already present in cart')
        return redirect('/foods/get_food_user')
    else:
        cart = Cart.objects.create(food=food, user=user)
        if cart:
            messages.add_message(request, messages.SUCCESS, 'Item added to cart')
            return redirect('/foods/mycart')
        else:
            messages.add_message(request, messages.ERROR, 'Unable to add item to cart')


@login_required
@user_only
def show_cart_items(request):
    user = request.user
    items = Cart.objects.filter(user= user)
    context = {
        'items':items,
        'activate_my_cart':'active'
    }
    return render(request, 'foods/mycart.html', context)

@login_required
@user_only
def remove_cart_item(request, cart_id):
    item = Cart.objects.get(id=cart_id)
    item.delete()
    messages.add_message(request, messages.SUCCESS, 'Cart item removed successfully')
    return redirect('/foods/mycart')


@login_required
@user_only
def order_form(request, food_id,cart_id):
    user = request.user
    food = Food.objects.get(id=food_id)
    cart_item = Cart.objects.get(id=cart_id)
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            quantity = request.POST.get('quantity')
            price = food.food_price
            total_price = int(quantity)*int(price)
            contact_no = request.POST.get('contact_no')
            contact_address = request.POST.get('contact_address')
            payment_method = request.POST.get('payment_method')
            order = Order.objects.create(food=food,
                                         user =user,
                                         quantity=quantity,
                                         total_price=total_price,
                                         contact_no = contact_no,
                                         contact_address =contact_address,
                                         status="Pending",
                                         payment_method= payment_method,
                                         payment_status=False
            )
            if order:
                # messages.add_message(request, messages.SUCCESS, 'Item Ordered. Continue Payment for Verification')
                # cart_item.delete()
                context = {
                    'order':order,
                    'cart':cart_item
                }
                return render(request, 'foods/esewa_payment.html', context)
        else:
            messages.add_message(request, messages.ERROR, 'Something went wrong')
            return render(request, 'foods/order_form.html', {'order_form':form})
    context = {
        'order_form': OrderForm
    }
    return render(request, 'foods/order_form.html', context)


import requests as req
def esewa_verify(request):
    import xml.etree.ElementTree as ET
    o_id = request.GET.get('oid')
    amount = request.GET.get('amt')
    refId = request.GET.get('refId')
    url = "https://uat.esewa.com.np/epay/transrec"
    d = {
        'amt': amount,
        'scd': 'EPAYTEST',
        'rid': refId,
        'pid': o_id,
    }
    resp = req.post(url, d)
    root = ET.fromstring(resp.content)
    status = root[0].text.strip()
    if status == 'Success':
        order_id = o_id.split("_")[0]
        order = Order.objects.get(id=order_id)
        order.payment_status = True
        order.save()
        cart_id = o_id.split("_")[1]
        cart = Cart.objects.get(id=cart_id)
        cart.delete()
        messages.add_message(request, messages.SUCCESS, 'Payment Successful')
        return redirect('/foods/mycart')
    else:
        messages.add_message(request, messages.ERROR, 'Unable to make payment')
        return redirect('/foods/mycart')


@login_required
@user_only
def my_order(request):
    user = request.user
    items = Order.objects.filter(user=user).order_by('-id')
    context = {
        'items':items,
        'activate_myorders':'active'
    }
    return render(request, 'foods/my_order.html', context)

food_ordering/foods/templates/foods/category_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
    <title>Add Category</title>
{% endblock%}

{% block main_content %}

<div class="container">
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Add New Category</h1>
          {% include 'messages.html'%}
        <div class="card py-2 px-2">
        <form class="form" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_category | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>
    </div>
    </div>
</div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = "Enter category name"
    form_fields[2].placeholder = "Enter category description"


   for(field in form_fields){
   form_fields[field].className += ' my-3'
   }
</script>

{% endblock %}

food_ordering/foods/templates/foods/category_update_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
    <title>Update Category</title>
{% endblock%}

{% block main_content %}

<div class="container">
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Update Category</h1>
          {% include 'messages.html'%}
        <div class="card py-2 px-2">
        <form class="form" action="" method="POST">
            {% csrf_token %}
            {{ form_category | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>
    </div>
    </div>
</div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = "Enter category name"
    form_fields[2].placeholder = "Enter category description"


   for(field in form_fields){
   form_fields[field].className += ' my-3'
   }
</script>

{% endblock %}

food_ordering/foods/templates/foods/esewa_payment.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
<title>Add Food</title>
{% endblock%}

{% block main_content %}

<div class="container">
    <div class="row">

        <div class="col-md-6 offset-md-3">
            <h1 class="text-center">You are being redirected to Esewa. Please wait.....</h1>
            <div class="card py-2 px-2" style="display:none;">
                <form action="https://uat.esewa.com.np/epay/main" method="POST" id="esewa_form">
                    <input value="{{order.total_price}}" name="tAmt" type="text" readonly>
                    <input value="{{order.total_price}}" name="amt" type="text" readonly>
                    <input value="0" name="txAmt" type="hidden" readonly>
                    <input value="0" name="psc" type="hidden" readonly>
                    <input value="0" name="pdc" type="hidden" readonly>
                    <input value="EPAYTEST" name="scd" type="hidden">
                    <input value="{{order.id}}_{{cart.id}}" name="pid" type="hidden">
                    <input value="http://127.0.0.1:8000/foods/esewa_verify" type="hidden" name="su">
                    <input value="{{request.build_absolute_uri}}" type="hidden" name="fu">
                    <input value="Submit" type="submit">
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    setTimeout(function(){
    document.getElementById('esewa_form').submit()
    }, 1000)

</script>
{% endblock %}

food_ordering/foods/templates/foods/food_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
    <title>Add Food</title>
{% endblock%}

{% block main_content %}

<div class="container">
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Add New Food</h1>
          {% include 'messages.html'%}
        <div class="card py-2 px-2">
        <form class="form" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_food | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>
    </div>
    </div>
</div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = "Enter food name"
    form_fields[2].placeholder = "Enter food price"


   for(field in form_fields){
   form_fields[field].className += ' my-3'
   }
</script>

{% endblock %}

food_ordering/foods/templates/foods/food_update_form.html
{% extends 'layout-admin.html' %}
{% load bootstrap %}
{% block title %}
    <title>Update Food</title>
{% endblock%}

{% block main_content %}

<div class="container">
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Update Food</h1>
          {% include 'messages.html'%}
        <div class="card py-2 px-2">
        <form class="form" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_food | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>
    </div>
    </div>
</div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = "Enter food name"
    form_fields[2].placeholder = "Enter food price"


   for(field in form_fields){
   form_fields[field].className += ' my-3'
   }
</script>

{% endblock %}

food_ordering/foods/templates/foods/get_category.html
{% extends 'layout-admin.html' %}
{% block title %}
<title>All Categories</title>
{% endblock%}

{% block main_content %}
<div class="container">
    <div class="row">

        <div class="col-md-10 offset-md-1">
            <h1 class="text-center">All Categories</h1>
            {% include 'messages.html' %}
            <div class="card py-2 px-2">
                <a class="btn btn-primary btn-sm ms-auto"
                href="/foods/category_form"
                >Add New Category</a>
                <table class="table-striped">
                    <tr>
                        <th>Category Name</th>
                        <th>Description</th>
                        <th>Date</th>
                        <th>Actions</th>
                    </tr>
                    {% for i in categories %}
                    <tr>
                        <td> {{ i.category_name }}</td>
                        <td> {{ i.category_description }}</td>
                        <td> {{ i.created_date }}</td>
                        <td><a class="btn btn-primary btn-sm" href="/foods/update_category/{{i.id}}">Edit</a> &nbsp;
                            <a class="btn btn-danger btn-sm"
                               href="/foods/delete_category/{{i.id}}"
                               onclick="return confirm('Are you sure want to delete this category?')" >Delete</a></td>

                    </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

food_ordering/foods/templates/foods/get_food.html
{% extends 'layout-admin.html' %}
{% block title %}
<title>All Foods</title>
{% endblock%}

{% block main_content %}
<div class="container">
    <div class="row">

        <div class="col-md-10 offset-md-1">
            <h1 class="text-center">All Foods</h1>
            {% include 'messages.html' %}
            <div class="card py-2 px-2">
                <a class="btn btn-primary btn-sm ms-auto"
                href="/foods/food_form"
                >Add New Food</a>
                <table class="table-striped">
                    <tr>
                        <th>Food Name</th>
                        <th>Price</th>
                        <th>Category</th>
                        <th>Image</th>

                        <th>Actions</th>
                    </tr>
                    {% for i in foods %}
                    <tr>
                        <td> {{ i.food_name }}</td>
                        <td> {{ i.food_price }}</td>
                        <td> {{ i.category.category_name }}</td>
                        <td><img src="/{{i.food_image}}" width="200"> </td>
                        <td><a class="btn btn-primary btn-sm" href="/foods/update_food/{{i.id}}">Edit</a> &nbsp;
                            <a class="btn btn-danger btn-sm"
                               href="/foods/delete_food/{{i.id}}"
                               onclick="return confirm('Are you sure want to delete this food?')" >Delete</a></td>

                    </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

food_ordering/foods/templates/foods/homepage.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
<title>Users Homepage</title>
{% endblock title %}

{% block main_content %}
<h1>User Dashboard</h1>
{% endblock main_content %}

food_ordering/foods/templates/foods/menu.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
<title>Menu</title>
{% endblock title %}

{% block main_content %}
<h1>All Categories With Foods</h1>
<div class="container">
    <div class="row justify-content-around">
        {% for i in categories %}
        <h1>{{i.category_name}}</h1>
          <div class="food_image">
       <img src="/{{i.category_image}}" width="200"/>
            </div>
        {% for j in i.food_set.all %}
        <div class="menu-items d-flex justify-content-between">
            <div class="food_name">
                <p>{{j.food_name}}</p>
            </div>
            <div class="food_price">
        Rs. {{j.food_price }}
            </div>

        </div>
        {% endfor %}

        {% endfor %}
    </div>
</div>
{% endblock main_content %}

food_ordering/foods/templates/foods/my_order.html
{% extends 'layout.html' %}
{% block title %}
<title>MyOrders</title>
{% endblock title %}
{% block main_content %}

<div class="container-fluid" style="min-height:300px;">
    <div class="row">
        <div class="col mt-4 mb-4">
            <h1 class="text-center text-uppercase m-4 font-weight-bold">My Order History</h1>
            {% include 'messages.html' %}
            <div class="card shadow-lg ">
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Item Name</th>
                            <th>Item Price</th>
                            <th>Quantity</th>
                            <th>Total Price</th>
                            <th>Ordered Date</th>
                            <th>Contact No</th>
                            <th>Delivery Location</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody class="align-items-center">
                        {% for item in items %}
                        <tr >
                            <td>{{item.food.food_name}}</td>
                            <td>Rs.{{item.food.price}}</td>
                            <td>{{item.quantity}}</td>
                            <td>{{item.total_price}}</td>
                            <td>{{item.created_date}}</td>
                            <td>{{item.contact_no}}</td>
                            <td>{{item.contact_address}}</td>
                            <td>{{item.status}}</td>
                                                    </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>

    </div>
</div>
</div>
{% endblock %}

food_ordering/foods/templates/foods/mycart.html
{% extends 'layout.html' %}
{% block title %}
<title>My Cart </title>
{% endblock%}

{% block main_content %}
<div class="container">
    <div class="row">

        <div class="col-md-10 offset-md-1">
            <h1 class="text-center">My Cart</h1>
            {% include 'messages.html' %}
            <div class="card py-2 px-2">
                <table class="table-striped">
                    <tr>
                        <th>Food Name</th>
                        <th>Food Price</th>
                        <th>Date Added</th>
                        <th>Actions</th>
                    </tr>
                    {% for i in items %}
                    <tr>
                        <td> {{ i.food.food_name }}</td>
                        <td> {{ i.food.food_price }}</td>
                        <td> {{ i.created_date }}</td>
                        <td><a class="btn btn-primary btn-sm" href="/foods/remove_cart_item/{{i.id}}">Remove</a> &nbsp;
                            <a class="btn btn-danger btn-sm"
                               href="/foods/order_form/{{i.food.id}}/{{i.id}}"
                               onclick="return confirm('Are you sure want to order this food?')" >Order</a></td>

                    </tr>
                    {% endfor %}

                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

food_ordering/foods/templates/foods/order_form.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% block title %}
    <title>Order Item</title>
{% endblock%}

{% block main_content %}

<div class="container">
<div class="row">

    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">Order Item</h1>
          {% include 'messages.html'%}
        <div class="card py-2 px-2">
        <form class="form" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ order_form | bootstrap_horizontal }}
            <button type="submit" class="btn btn-primary mt-3">Proceed to Payment</button>
        </form>
    </div>
    </div>
</div>
</div>
<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = "Enter quantity"
    form_fields[2].placeholder = "Enter contact no"
       form_fields[3].placeholder = "Enter contact address"


   for(field in form_fields){
   form_fields[field].className += ' my-3'
   }
</script>

{% endblock %}

food_ordering/foods/templates/foods/show_categories.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
<title>Foods</title>
{% endblock title %}

{% block main_content %}
<h1>All Categories</h1>
<div class="container">
    <div class="row justify-content-around">
        {% for i in categories %}
        <div class="card col-md-3">
<!--            <img src="/{{i.food_image}}" class="card-img-top" alt="...">-->
            <div class="card-body">
                <h5 class="card-title">{{i.category_name}}</h5>
                <p class="card-text">{{i.category_description}}</p>
                <a href="#" class="btn btn-primary">View Details</a>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock main_content %}

food_ordering/foods/templates/foods/show_foods.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
<title>Foods</title>
{% endblock title %}

{% block main_content %}
<h1>All Foods</h1>
<div class="container">
    <div class="row justify-content-around">
        {% include 'messages.html' %}
        {% for i in foods %}
        <div class="card col-md-3 m-3">
            <img src="/{{i.food_image}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{i.food_name}}</h5>
                <p class="card-text">Rs. {{i.food_price}}</p>
                 <p class="card-text">{{i.category.category_name}}</p>
                <a href="/foods/add_to_cart/{{i.id}}" class="btn btn-primary"
                onclick="return confirm('Are you sure want to add this item to cart?')">Add to Cart</a>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock main_content %}